version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run server
    ports:
      - 3001:3001

  client:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run client
    ports:
      - 3000:3000
      